[nfs]
10.16.39.182 ansible_ssh_user='ec2-user'

[webservers]
10.16.34.50 ansible_ssh_user='ec2-user'
10.16.47.168 ansible_ssh_user='ec2-user'

[db]
10.16.42.150 ansible_ssh_user='ubuntu'

[lb]
10.16.45.80 ansible_ssh_user='ubuntu'