[nfs]
10.16.42.158 ansible_ssh_user='ec2-user'

[webservers]
10.16.40.101 ansible_ssh_user='ec2-user'
10.16.32.64 ansible_ssh_user='ec2-user'

[db]
10.16.43.197 ansible_ssh_user='ubuntu'

[lb]
10.16.34.221 ansible_ssh_user='ubuntu'