[uat-webservers]

web01 ansible_host=172.31.25.185 ansible_ssh_user='ec2-user'
web02 ansible_host=172.31.22.168 ansible_ssh_user='ec2-user'
db01 ansible_host=172.31.28.204 ansible_ssh_user='ubuntu'
lb01 ansible_host=172.31.7.29 ansible_ssh_user='ubuntu'


[webservers]
web01
web02

[dbserver]
db01

[lb]
lb01

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/monitoring.pem

