---
- name: update web and nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
  - name: Update and upgrade packages for RedHat Servers
    yum: 
      name: '*'
      state: latest
  - name: ensure wireshark is at the latest version
    yum:
      name: wireshark
      state: latest
  - name: Set Timezone to Europe/London
    timezone:
      name: Europe/London

- name: Create Directory and file inside it for webservers
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
  - name: Create /var/www on webservers
    ansible.builtin.file:
      path: /var/www
      state: directory
      mode: "u=rw,g=wx,o=rwx"
  - name: Create file inside /var/www directory
    ansible.builtin.file:
      path: /var/www/wale.txt
      state: touch
      mode: "u=rw,g=wx,o=rwx"

- name: update db and lb server
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: Update Repository Index
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
      upgrade: dist
  - name: ensure wireshark is at the latest version
    apt:
      name: wireshark
      state: latest
  - name: Set Timezone to Europe/London
    timezone:
      name: Europe/London