---
- hosts: all
- name: Import common file
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- name: Import env-vars file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Import database file
  import_playbook: ../static-assignments/db.yml

- name: Import webservers file
  import_playbook: ../static-assignments/webservers.yml

- name: Import loadbalancer file
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
